### ISSUE TITLE
Can we not do this approach?

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#574] opened 2023-08-14 16:12 UTC
https://github.com/tokitou-san/CoreProject-V3-UI/blob/e1f8a3db81a7afb4b4e67e3e95b5c54b01235f06/src/lib/components/tippies/filter_options.svelte#L1-L42

**Comment by tokitou-san** [comment] 2023-08-15 03:37
Meaning? change tippy approach?

**Comment by baseplate-admin** [comment] 2023-08-15 03:48
Yea dont use tippy for everything. Tippy is pretty performance intensive

**Comment by tokitou-san** [comment] 2023-08-15 04:02
> Tippy is pretty performance intensive

Yea? also it seems values which are passed to tippy once is not updating.

**Comment by baseplate-admin** [comment] 2023-08-15 04:10
> Yea? also it seems values which are passed to tippy once is not updating.

I can fix this. But still in general i dont like relying too much on a tooltip library

**Comment by tokitou-san** [comment] 2023-08-15 04:13
> I can fix this. But still in general i dont like relying too much on a tooltip library

Okay? want to use skeleton this time? or make a custom uhh?

**Comment by baseplate-admin** [comment] 2023-08-15 04:15
> Okay? want to use skeleton this time? or make a custom uhh?

Do you think skeleton popup issue is fixed?

**Comment by tokitou-san** [comment] 2023-08-15 04:18
> Do you think skeleton popup issue is fixed?

No? I will take a look
also that flick animation on first click seems not fixed...

**Comment by baseplate-admin** [comment] 2023-08-30 02:58
tied to :

* https://github.com/tokitou-san/CoreProject-V3-UI/issues/574

**Comment by tokitou-san** [comment] 2023-09-01 13:07
Duplicate of #603

**Closed by tokitou-san** 2023-09-01 13:07 UTC
Labels: enhancement, help wanted, good first issue, question
